import os
from .models import Dataset
from .serializers import DatasetSerializer
from .utils import analyze_csv
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from datetime import datetime
from django.contrib.auth.models import User
from django.http import FileResponse
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view,permission_classes,parser_classes
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

@api_view(['POST'])
@permission_classes([IsAuthenticated])
@parser_classes([MultiPartParser, FormParser])
def upload_csv(request):
    file=request.FILES['file']
    if not file:
        return Response({"error": "No file uploaded"}, status=400)

    upload_dir = 'media/uploads'
    os.makedirs(upload_dir, exist_ok=True) 
    file_path = os.path.join(upload_dir, file.name)
    with open(file_path,'wb+') as dest:
        for chunk in file.chunks():
            dest.write(chunk)
    
    summary = analyze_csv(file_path)

    dataset = Dataset.objects.create(
        file=file,
        **summary
    )

    # delete older datasets>5 
    qs= Dataset.objects.all()
    if qs.count() >5:
        for obj in qs[5:]:
            obj.delete()

    return Response(DatasetSerializer(dataset).data)


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def summary(request):
    return Response(DatasetSerializer(Dataset.objects.all(),many=True).data)


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def generate_pdf(request,id):
    dataset=Dataset.objects.get(id=id)
    upload_dir = 'media/reports'
    os.makedirs(upload_dir, exist_ok=True) 
    pdf_path = f"media/reports/report_{id}.pdf"

    

    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 1.2 * inch,
                        "CHEMICAL EQUIPMENT ANALYSIS REPORT")

    c.setFont("Helvetica", 10)
    c.drawCentredString(
        width / 2,
        height - 1.5 * inch,
        f"Generated on {datetime.now().strftime('%d %b %Y, %H:%M')}"
    )

    c.line(1 * inch, height - 1.7 * inch, width - 1 * inch, height - 1.7 * inch)

    y = height - 2.2 * inch
    c.setFont("Helvetica", 12)

    def draw_row(label, value,y):
         
        c.drawString(1.2 * inch, y, label)
        c.drawString(4 * inch, y, str(value))

    draw_row("Dataset ID", id,y)
    y -= 0.35 * inch
    
    draw_row("Upload Date", dataset.uploaded_at.strftime("%d %b %Y"),y)
    y -= 0.35 * inch
    
    draw_row("Total Records", dataset.total_count,y)
    y -= 0.35 * inch
    
    draw_row("Avg Flowrate", f"{dataset.avg_flowrate:.2f}",y)
    
    y -= 0.35 * inch
    draw_row("Avg Pressure", f"{dataset.avg_pressure:.2f}",y)
    
    y -= 0.35 * inch
    draw_row("Avg Temperature", f"{dataset.avg_temperature:.2f}",y)

    y -= 0.35 * inch

    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(
        width / 2,
        0.75 * inch,
        "Generated by Chemical Equipment Visualizer"
    )

    c.save()

    return FileResponse( open(pdf_path, 'rb'),
        content_type='application/pdf',
        as_attachment=True,
        filename=f"report_{id}.pdf")

# signup
@api_view(["POST"])
def signup(request):
    username=request.data.get("username")
    password=request.data.get("password")

    if not username or not password:
        return Response(
            {"error":"Username And Password Required"}
            ,status=status.HTTP_400_BAD_REQUEST
        )
    if User.objects.filter(username=username).exists():
        return Response(
            {"error":"Username already exists"}
            ,status=status.HTTP_400_BAD_REQUEST
        )
    
    user=User.objects.create_user(username=username,password=password)

    return Response({"message","User created Successfully"},
                    status=status.HTTP_201_CREATED)